language: node_js
node_js:
- '6.11.3'
install: npm install
before_script:
- git config --global user.name "mathxlee"
- git config --global user.email "math.lee@qq.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml
script: npm run deploy